In [1]:
import numpy as np
import pandas as pd

In [3]:
s=pd.Series(np.random.randint(0,10,5))
s

0    3
1    5
2    8
3    4
4    5
dtype: int32

In [4]:
df = pd.DataFrame(np.random.randint(0,10,(3,3)),
                 columns=['A','B','C'])
df

A  B  C
0  3  9  5
1  4  1  3
2  3  8  2

In [5]:
np.exp(s)

0      20.085537
1     148.413159
2    2980.957987
3      54.598150
4     148.413159
dtype: float64

In [6]:
np.cos(df*np.pi/4)

A         B             C
0 -0.707107  0.707107 -7.071068e-01
1 -1.000000  0.707107 -7.071068e-01
2 -0.707107  1.000000  6.123234e-17

In [7]:
#인덱스가 같은 것 끼리 더해준다
s1 = pd.Series([1,3,5,7,9],index=[0,1,2,3,4])
s2 = pd.Series([2,4,6,8,10],index=[1,2,3,4,5])
s1 + s2

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [8]:
#누락값을 지정해준다
s1.add(s2,fill_value=0)

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [14]:
df1=pd.DataFrame(np.random.randint(0,20,(3,3)),
                columns=list('ACD'))
df1

A   C   D
0  12  14  16
1   8  13   1
2   4  17   4

In [10]:
df2=pd.DataFrame(np.random.randint(0,20,(5,5)),
                columns=list('BAECD'))
df2

B   A   E   C   D
0  12  18   3   0  10
1   5  18   5  19  15
2  10   6   2  13  19
3  13   2  11   1   0
4  13  15   8  16  17

In [11]:
df1 + df2

A   B     C     D   E
0  23.0 NaN  19.0  10.0 NaN
1  22.0 NaN  25.0  27.0 NaN
2  10.0 NaN  32.0  34.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [12]:
fvalue = df1.stack().mean()
df1.add(df2,fill_value=fvalue)

A          B          C          D          E
0  23.000000  21.333333  19.000000  10.000000  12.333333
1  22.000000  14.333333  25.000000  27.000000  14.333333
2  10.000000  19.333333  32.000000  34.000000  11.333333
3  11.333333  22.333333  10.333333   9.333333  20.333333
4  24.333333  22.333333  25.333333  26.333333  17.333333

In [15]:
a = np.random.randint(1,10,size=(3,3))
a

array([[2, 6, 6],
       [2, 6, 3],
       [7, 3, 3]])

In [16]:
#넘파이에서 연산
a + a[0] #브로드캐스팅 돼서 1행이 전부 더해졌다

array([[ 4, 12, 12],
       [ 4, 12,  9],
       [ 9,  9,  9]])

In [17]:
df = pd.DataFrame(a,columns=list('ABC'))
df

A  B  C
0  2  6  6
1  2  6  3
2  7  3  3

In [18]:
#판다스에서 연산
df + df.iloc[0]

A   B   C
0  4  12  12
1  4  12   9
2  9   9   9

In [20]:
df.add(df.iloc[0])

A   B   C
0  4  12  12
1  4  12   9
2  9   9   9

In [22]:
 a

array([[2, 6, 6],
       [2, 6, 3],
       [7, 3, 3]])

In [23]:
a - a[0]

array([[ 0,  0,  0],
       [ 0,  0, -3],
       [ 5, -3, -3]])

In [24]:
df

A  B  C
0  2  6  6
1  2  6  3
2  7  3  3

In [25]:
df - df.iloc[0]

A  B  C
0  0  0  0
1  0  0 -3
2  5 -3 -3

In [26]:
df.sub(df.iloc[0])

A  B  C
0  0  0  0
1  0  0 -3
2  5 -3 -3

In [29]:
df.subtract(df['B'],axis=0)

A  B  C
0 -4  0  0
1 -4  0 -3
2  4  0  0

In [30]:
a

array([[2, 6, 6],
       [2, 6, 3],
       [7, 3, 3]])

In [31]:
a * a[0]

array([[ 4, 36, 36],
       [ 4, 36, 18],
       [14, 18, 18]])

In [32]:
df

A  B  C
0  2  6  6
1  2  6  3
2  7  3  3

In [33]:
df * df.iloc[1]

A   B   C
0   4  36  18
1   4  36   9
2  14  18   9

In [34]:
df.mul(df.iloc[1])

A   B   C
0   4  36  18
1   4  36   9
2  14  18   9

In [35]:
df.multiply(df.iloc[1])

A   B   C
0   4  36  18
1   4  36   9
2  14  18   9

In [36]:
a

array([[2, 6, 6],
       [2, 6, 3],
       [7, 3, 3]])

In [37]:
a/a[0]

array([[1. , 1. , 1. ],
       [1. , 1. , 0.5],
       [3.5, 0.5, 0.5]])

In [38]:
df / df.iloc[0]

A    B    C
0  1.0  1.0  1.0
1  1.0  1.0  0.5
2  3.5  0.5  0.5

In [39]:
df.truediv(df.iloc[0])

A    B    C
0  1.0  1.0  1.0
1  1.0  1.0  0.5
2  3.5  0.5  0.5

In [40]:
df.div(df.iloc[1])

A    B    C
0  1.0  1.0  2.0
1  1.0  1.0  1.0
2  3.5  0.5  1.0

In [41]:
a // a[0]

array([[1, 1, 1],
       [1, 1, 0],
       [3, 0, 0]], dtype=int32)

In [42]:
df.floordiv(df.iloc[0])

A  B  C
0  1  1  1
1  1  1  0
2  3  0  0

In [43]:
a

array([[2, 6, 6],
       [2, 6, 3],
       [7, 3, 3]])

In [45]:
a%a[0]

array([[0, 0, 0],
       [0, 0, 3],
       [1, 3, 3]], dtype=int32)

In [46]:
df.mod(df.iloc[0])

A  B  C
0  0  0  0
1  0  0  3
2  1  3  3

In [47]:
a

array([[2, 6, 6],
       [2, 6, 3],
       [7, 3, 3]])

In [48]:
a**a[0]

array([[    4, 46656, 46656],
       [    4, 46656,   729],
       [   49,   729,   729]], dtype=int32)

In [49]:
df.pow(df.iloc[0])

A      B      C
0   4  46656  46656
1   4  46656    729
2  49    729    729

In [53]:
df

A  B  C
0  2  6  6
1  2  6  3
2  7  3  3

In [51]:
row = df.iloc[0,::2]
row

A    2
C    6
Name: 0, dtype: int32

In [52]:
df - row

A   B    C
0  0.0 NaN  0.0
1  0.0 NaN -3.0
2  5.0 NaN -3.0

In [54]:
####정렬

In [55]:
s = pd.Series(range(5),index=['A','D','B','C','E'])
s

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [56]:
s.sort_index()

A    0
B    2
C    3
D    1
E    4
dtype: int64

In [57]:
s.sort_values()

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [58]:
df = pd.DataFrame(np.random.randint(0,10,(4,4)),
                 index=[2,4,1,3],
                 columns=list('BDAC'))
df

B  D  A  C
2  1  9  0  6
4  0  6  0  0
1  5  0  1  0
3  8  0  3  8

In [59]:
df.sort_index()

B  D  A  C
1  5  0  1  0
2  1  9  0  6
3  8  0  3  8
4  0  6  0  0

In [60]:
df.sort_values(by='A') #2차원이기 때문에 기준을 정해줬다

B  D  A  C
2  1  9  0  6
4  0  6  0  0
1  5  0  1  0
3  8  0  3  8

In [61]:
df.sort_values(by=['A','C'])

B  D  A  C
4  0  6  0  0
2  1  9  0  6
1  5  0  1  0
3  8  0  3  8

In [62]:
df.sort_index(axis=1) #정렬되는 인덱스의 축을 지정할 수 있다.

A  B  C  D
2  0  1  6  9
4  0  0  0  6
1  1  5  0  0
3  3  8  8  0

In [63]:
s = pd.Series([-2,4,7,3,0,7,5,-4,2,6])
s

0   -2
1    4
2    7
3    3
4    0
5    7
6    5
7   -4
8    2
9    6
dtype: int64

In [64]:
s.rank() #기본값은 작은게 1번

0    2.0
1    6.0
2    9.5
3    5.0
4    3.0
5    9.5
6    7.0
7    1.0
8    4.0
9    8.0
dtype: float64

In [65]:
s.rank(method='first') #동일한 값이면 먼저 적힌게 순위를 더 높힌다.

0     2.0
1     6.0
2     9.0
3     5.0
4     3.0
5    10.0
6     7.0
7     1.0
8     4.0
9     8.0
dtype: float64

In [66]:
s.rank(method='max') #같은 값을 가지는 순위를 반올림해준다

0     2.0
1     6.0
2    10.0
3     5.0
4     3.0
5    10.0
6     7.0
7     1.0
8     4.0
9     8.0
dtype: float64

In [80]:
###고성능 연산 -> eval, query 메서드

In [67]:
nrows, ncols = 100000,100
df1,df2,df3,df4 = (pd.DataFrame(np.random.rand(nrows,ncols)) for i in range(4))

In [68]:
%timeit df1 +df2+df3+df4

95.6 ms ± 1.98 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [69]:
#string 형태를 연산해준다 - pd의 고성능 연산
%timeit pd.eval('df1 + df2 +df3 +df4')

42.3 ms ± 2.56 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [70]:
df=pd.DataFrame(np.random.rand(1000000,5),
               columns=['A','B','C','D','E'])
df.head()

A         B         C         D         E
0  0.095089  0.810516  0.089661  0.837761  0.799645
1  0.133468  0.599132  0.873163  0.265895  0.325012
2  0.816247  0.693560  0.281491  0.655627  0.274967
3  0.707527  0.217442  0.999933  0.373198  0.468055
4  0.527518  0.651922  0.913004  0.816054  0.262729

In [71]:
df.eval('R = A + B / C - D  * E ', inplace=True)
df.head()

A         B         C         D         E         R
0  0.095089  0.810516  0.089661  0.837761  0.799645  8.464935
1  0.133468  0.599132  0.873163  0.265895  0.325012  0.733212
2  0.816247  0.693560  0.281491  0.655627  0.274967  3.099848
3  0.707527  0.217442  0.999933  0.373198  0.468055  0.750306
4  0.527518  0.651922  0.913004  0.816054  0.262729  1.027157

In [72]:
col_mean = df.mean(1)
df['A'] + col_mean

0         1.944690
1         0.621781
2         1.786537
3         1.293603
4         1.227249
            ...   
999995    1.460759
999996    0.630927
999997    1.089560
999998    1.656253
999999    1.236327
Length: 1000000, dtype: float64

In [73]:
df.eval('A + @col_mean')

0         1.944690
1         0.621781
2         1.786537
3         1.293603
4         1.227249
            ...   
999995    1.460759
999996    0.630927
999997    1.089560
999998    1.656253
999999    1.236327
Length: 1000000, dtype: float64

In [75]:
df[(df.A < 0.5) & (df.B < 0.5) & (df.C > 0.5)]

A         B         C         D         E         R
6       0.347191  0.267740  0.629216  0.239540  0.852523  0.568491
9       0.003585  0.363912  0.706268  0.443896  0.284891  0.392384
11      0.130478  0.080713  0.687941  0.978462  0.629698 -0.368332
13      0.364305  0.094117  0.904746  0.031457  0.941779  0.438705
26      0.122727  0.457816  0.605624  0.628649  0.501462  0.563424
...          ...       ...       ...       ...       ...       ...
999956  0.351704  0.001313  0.610128  0.988800  0.018809  0.335257
999966  0.435992  0.018239  0.745123  0.365491  0.000004  0.460468
999982  0.397729  0.259189  0.770126  0.548537  0.178986  0.636103
999990  0.483407  0.179589  0.901540  0.136334  0.146204  0.662677
999992  0.340879  0.345047  0.670389  0.427165  0.126994  0.801328

[125291 rows x 6 columns]

In [76]:
pd.eval('df[(df.A < 0.5) & (df.B < 0.5) & (df.C > 0.5)]')

A         B         C         D         E         R
6       0.347191  0.267740  0.629216  0.239540  0.852523  0.568491
9       0.003585  0.363912  0.706268  0.443896  0.284891  0.392384
11      0.130478  0.080713  0.687941  0.978462  0.629698 -0.368332
13      0.364305  0.094117  0.904746  0.031457  0.941779  0.438705
26      0.122727  0.457816  0.605624  0.628649  0.501462  0.563424
...          ...       ...       ...       ...       ...       ...
999956  0.351704  0.001313  0.610128  0.988800  0.018809  0.335257
999966  0.435992  0.018239  0.745123  0.365491  0.000004  0.460468
999982  0.397729  0.259189  0.770126  0.548537  0.178986  0.636103
999990  0.483407  0.179589  0.901540  0.136334  0.146204  0.662677
999992  0.340879  0.345047  0.670389  0.427165  0.126994  0.801328

[125291 rows x 6 columns]

In [77]:
#질의문을 사용한 인덱싱
df.query('(A < 0.5) and (B < 0.5) and (C > 0.5)')

A         B         C         D         E         R
6       0.347191  0.267740  0.629216  0.239540  0.852523  0.568491
9       0.003585  0.363912  0.706268  0.443896  0.284891  0.392384
11      0.130478  0.080713  0.687941  0.978462  0.629698 -0.368332
13      0.364305  0.094117  0.904746  0.031457  0.941779  0.438705
26      0.122727  0.457816  0.605624  0.628649  0.501462  0.563424
...          ...       ...       ...       ...       ...       ...
999956  0.351704  0.001313  0.610128  0.988800  0.018809  0.335257
999966  0.435992  0.018239  0.745123  0.365491  0.000004  0.460468
999982  0.397729  0.259189  0.770126  0.548537  0.178986  0.636103
999990  0.483407  0.179589  0.901540  0.136334  0.146204  0.662677
999992  0.340879  0.345047  0.670389  0.427165  0.126994  0.801328

[125291 rows x 6 columns]

In [78]:
col_mean = df['D'].mean()
df[(df.A < col_mean) & (df.B < col_mean)]

A         B         C         D         E         R
6       0.347191  0.267740  0.629216  0.239540  0.852523  0.568491
9       0.003585  0.363912  0.706268  0.443896  0.284891  0.392384
11      0.130478  0.080713  0.687941  0.978462  0.629698 -0.368332
13      0.364305  0.094117  0.904746  0.031457  0.941779  0.438705
17      0.098970  0.205187  0.422329  0.887434  0.823350 -0.145851
...          ...       ...       ...       ...       ...       ...
999966  0.435992  0.018239  0.745123  0.365491  0.000004  0.460468
999982  0.397729  0.259189  0.770126  0.548537  0.178986  0.636103
999990  0.483407  0.179589  0.901540  0.136334  0.146204  0.662677
999992  0.340879  0.345047  0.670389  0.427165  0.126994  0.801328
999996  0.277278  0.151624  0.308612  0.498569  0.233776  0.652032

[250593 rows x 6 columns]

In [79]:
df.query('A < @col_mean and B < @col_mean')

A         B         C         D         E         R
6       0.347191  0.267740  0.629216  0.239540  0.852523  0.568491
9       0.003585  0.363912  0.706268  0.443896  0.284891  0.392384
11      0.130478  0.080713  0.687941  0.978462  0.629698 -0.368332
13      0.364305  0.094117  0.904746  0.031457  0.941779  0.438705
17      0.098970  0.205187  0.422329  0.887434  0.823350 -0.145851
...          ...       ...       ...       ...       ...       ...
999966  0.435992  0.018239  0.745123  0.365491  0.000004  0.460468
999982  0.397729  0.259189  0.770126  0.548537  0.178986  0.636103
999990  0.483407  0.179589  0.901540  0.136334  0.146204  0.662677
999992  0.340879  0.345047  0.670389  0.427165  0.126994  0.801328
999996  0.277278  0.151624  0.308612  0.498569  0.233776  0.652032

[250593 rows x 6 columns]

In [81]:
###데이터 결합

In [83]:
s1 = pd.Series(['a','b'],index=[1,2])
s2 = pd.Series(['c','d'],index=[3,4])
pd.concat([s1,s2])

1    a
2    b
3    c
4    d
dtype: object

In [84]:
def create_df(cols,idx):
    data = {c : [str(c.lower()) + str(i) for i in idx] for c in cols}
    return pd.DataFrame(data,idx)

In [85]:
df1 = create_df('AB',[1,2])
df1

A   B
1  a1  b1
2  a2  b2

In [86]:
df2 = create_df('AB',[3,4])
df2

A   B
3  a3  b3
4  a4  b4

In [87]:
pd.concat([df1,df2])

A   B
1  a1  b1
2  a2  b2
3  a3  b3
4  a4  b4

In [88]:
df3 = create_df('AB',[0,1])
df3

A   B
0  a0  b0
1  a1  b1

In [89]:
df4 = create_df('CD',[0,1])
df4

C   D
0  c0  d0
1  c1  d1

In [90]:
#인덱스가 같아서 결합은 하지만 누락값은 존재한다
pd.concat([df3,df4])

A    B    C    D
0   a0   b0  NaN  NaN
1   a1   b1  NaN  NaN
0  NaN  NaN   c0   d0
1  NaN  NaN   c1   d1

In [100]:
pd.concat([df3,df4],axis=1)

A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1

In [93]:
#값이 오버랩되는 부분이 있으면 오류를 발생시킨다
pd.concat([df1,df3],verify_integrity=True)

ValueError: Indexes have overlapping values: Int64Index([1], dtype='int64')

In [94]:
#인덱스를 무시하고 강제로 합친다
pd.concat([df1,df3],ignore_index=True)

A   B
0  a1  b1
1  a2  b2
2  a0  b0
3  a1  b1

In [95]:
#별도의 key를 지정해줘서 혼란을 피할 수 도 있다
pd.concat([df1,df3],keys=['x','y'])

A   B
x 1  a1  b1
  2  a2  b2
y 0  a0  b0
  1  a1  b1

In [96]:
df5=create_df('ABC',[1,2])
df6=create_df('BCD',[3,4])
pd.concat([df5,df6])

A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

In [98]:
#실질적인 데이터가 존재하는 부분만 합쳐준다
pd.concat([df5,df6],join='inner')

B   C
1  b1  c1
2  b2  c2
3  b3  c3
4  b4  c4

In [99]:
df5.append(df6)

A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

In [101]:
###병합과 조인

In [103]:
df1 = pd.DataFrame({'학생':['홍길동','이순신','임꺽정','김유신'],
                    '학과':['경영학과','교육학과','컴퓨터학과','통계학과']})
df1

학생     학과
0  홍길동   경영학과
1  이순신   교육학과
2  임꺽정  컴퓨터학과
3  김유신   통계학과

In [104]:
df2 = pd.DataFrame({'학생':['홍길동','이순신','임꺽정','김유신'],
                    '입학년도':['2012','2016','2019','2020']})
df2

학생  입학년도
0  홍길동  2012
1  이순신  2016
2  임꺽정  2019
3  김유신  2020

In [105]:
df3 = pd.merge(df1,df2)
df3

학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [106]:
df4 = pd.DataFrame({'학과':['경영학과','교육학과','컴퓨터학과','통계학과'],
                   '학과장':['황희','장영실','안창호','정약용']})
df4

학과  학과장
0   경영학과   황희
1   교육학과  장영실
2  컴퓨터학과  안창호
3   통계학과  정약용

In [107]:
pd.merge(df3,df4)

학생     학과  입학년도  학과장
0  홍길동   경영학과  2012   황희
1  이순신   교육학과  2016  장영실
2  임꺽정  컴퓨터학과  2019  안창호
3  김유신   통계학과  2020  정약용

In [108]:
df5 = pd.DataFrame({'학과':['경영학과','교육학과','교육학과','컴퓨터학과','컴퓨터학과','통계학과'],
                   '과목':['경영개론','기초수학','물리학','프로그래밍','운영체제','확률론']})
df5

학과     과목
0   경영학과   경영개론
1   교육학과   기초수학
2   교육학과    물리학
3  컴퓨터학과  프로그래밍
4  컴퓨터학과   운영체제
5   통계학과    확률론

In [109]:
pd.merge(df1,df5)

학생     학과     과목
0  홍길동   경영학과   경영개론
1  이순신   교육학과   기초수학
2  이순신   교육학과    물리학
3  임꺽정  컴퓨터학과  프로그래밍
4  임꺽정  컴퓨터학과   운영체제
5  김유신   통계학과    확률론

In [111]:
pd.merge(df1,df2,on='학생')

학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [113]:
df6 = pd.DataFrame({'이름':['홍길동','이순신','임꺽정','김유신'],
                    '성적':['A','A+','B','B+']})
df6

이름  성적
0  홍길동   A
1  이순신  A+
2  임꺽정   B
3  김유신  B+

In [114]:

pd.merge(df1,df6,left_on="학생",right_on='이름')

학생     학과   이름  성적
0  홍길동   경영학과  홍길동   A
1  이순신   교육학과  이순신  A+
2  임꺽정  컴퓨터학과  임꺽정   B
3  김유신   통계학과  김유신  B+

In [116]:
#같은 값을 공유하는 열끼리 합칠때, 중복되는 값을 제외하고 싶다면 drop 메서드를 사용한다
pd.merge(df1,df6,left_on='학생',right_on='이름').drop('이름',axis=1)

학생     학과  성적
0  홍길동   경영학과   A
1  이순신   교육학과  A+
2  임꺽정  컴퓨터학과   B
3  김유신   통계학과  B+

In [117]:
mdf1 = df1.set_index('학생')
mdf2 = df2.set_index('학생')

In [118]:
mdf1

학과
학생        
홍길동   경영학과
이순신   교육학과
임꺽정  컴퓨터학과
김유신   통계학과

In [119]:
mdf2

입학년도
학생       
홍길동  2012
이순신  2016
임꺽정  2019
김유신  2020

In [120]:
pd.merge(mdf1,mdf2,left_index=True,right_index=True)

학과  입학년도
학생              
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [121]:
mdf1.join(mdf2)

학과  입학년도
학생              
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [123]:
#인덱스와 열이름끼리도 결합이 가능하다
pd.merge(mdf1,df6,left_index=True,right_on='이름')

학과   이름  성적
0   경영학과  홍길동   A
1   교육학과  이순신  A+
2  컴퓨터학과  임꺽정   B
3   통계학과  김유신  B+

In [124]:
df7 = pd.DataFrame({'이름':['홍길동','이순신','임꺽정'],
                   '주문음식':['햄버거','피자','짜장면']})
df7

이름 주문음식
0  홍길동  햄버거
1  이순신   피자
2  임꺽정  짜장면

In [125]:
df8 = pd.DataFrame({'이름':['홍길동','이순신','김유신'],
                   '주문음료':['콜라','사이다','커피']})
df8

이름 주문음료
0  홍길동   콜라
1  이순신  사이다
2  김유신   커피

In [126]:
#데이터가 둘 다 있는 열만 가져온다
pd.merge(df7,df8)

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다

In [127]:
pd.merge(df7,df8,how='inner')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다

In [128]:
#누락된 테이터라도 다 합쳐준다
pd.merge(df7,df8,how='outer')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  임꺽정  짜장면  NaN
3  김유신  NaN   커피

In [129]:
#df7을 기준으로 해서 더해준다
pd.merge(df7,df8,how='left')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  임꺽정  짜장면  NaN

In [130]:
pd.merge(df7,df8,how='right')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  김유신  NaN   커피

In [131]:
df9 = pd.DataFrame({'이름':['홍길동','이순신','임꺽정','김유신'],
                   '순위':[3,2,4,1]})
df9

이름  순위
0  홍길동   3
1  이순신   2
2  임꺽정   4
3  김유신   1

In [132]:
df10 = pd.DataFrame({'이름':['홍길동','이순신','임꺽정','김유신'],
                   '순위':[4,1,3,2]})
df10

이름  순위
0  홍길동   4
1  이순신   1
2  임꺽정   3
3  김유신   2

In [133]:
pd.merge(df9,df10,on='이름')

이름  순위_x  순위_y
0  홍길동     3     4
1  이순신     2     1
2  임꺽정     4     3
3  김유신     1     2

In [134]:
#접미사를 붙여서 조질 수도 있다
pd.merge(df9,df10,on='이름',suffixes=["_인기","_성적"])

이름  순위_인기  순위_성적
0  홍길동      3      4
1  이순신      2      1
2  임꺽정      4      3
3  김유신      1      2

In [ ]:
#2:12;20