In [1]:
import numpy as np

In [2]:
name=['Alice','Bob','Cathy','Doug'] #각 데이터간의 연관성을 파악하기 힘들다
age=[25,45,37,19]
weight=[55.0,85.5,68.0,61.5]

In [30]:
x=np.zeros(4,dtype=int) #내용이 없는 구조화 된 배열 생성
x

array([0, 0, 0, 0])

In [4]:
x

array([0, 0, 0, 0])

In [5]:
data=np.zeros(4,dtype={'names':('이름','나이','몸무게'),'formats':('U10','i4','f8')})
print(data.dtype)

[('이름', '<U10'), ('나이', '<i4'), ('몸무게', '<f8')]


In [6]:
data #('',0,0.)

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('이름', '<U10'), ('나이', '<i4'), ('몸무게', '<f8')])

In [7]:
data['이름']=name
data['나이']=age
data['몸무게']=weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [8]:
data['이름'] #이름으로 인덱싱

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [9]:
data[0] #인덱스 번호로 인덱싱

('Alice', 25, 55.)

In [10]:
data[3]['이름'] #4번째 칸에서 이름 칸 인덱싱

'Doug'

In [31]:
data[data['나이']<30]['이름'] #나이가 30살 미만인 사람의 이름

array(['Alice', 'Doug'], dtype='<U10')

In [20]:
dat=np.zeros(4,dtype=dt)

In [21]:
dat

array([(b'', 0, 0.), (b'', 0, 0.), (b'', 0, 0.), (b'', 0, 0.)],
      dtype=[('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

In [40]:
dt=np.dtype({'names':('이름','나이','몸무게'),'formats':('U10','i4','f8')}) #데이터 타입 지정 방법1-딕셔너리 형태

In [41]:
dt=np.dtype({'names':('이름','나이','몸무게'),'formats':((np.str_,10),int,np.float32)}) #데이터 타입 지정 방법2 - 넘파이 데이터 형태

In [42]:
dt=np.dtype([('이름','S10'),('나이','i4'),('몸무게','f8')]) #데이터 타입 지정 방법 - 튜플의 리스트
dt

dtype([('이름', 'S10'), ('나이', '<i4'), ('몸무게', '<f8')])

In [43]:
dt=np.dtype('S10,i4,f8')
dt

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

In [23]:
tp=np.dtype([('id','i8'),('mat','f8',(3,3))]) #행렬을 담을 수 있다
X=np.zeros(1,dtype=tp)
print(X[0])
print(X['mat'][0]) #배열 안에 있는 행렬 불러오기

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
X

array([(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])],
      dtype=[('id', '<i8'), ('mat', '<f8', (3, 3))])

In [25]:
X['mat'][0][1,1]

0.0

In [32]:
data['나이']

array([25, 45, 37, 19])

In [33]:
data_rec=data.view(np.recarray)
data_rec.나이

array([25, 45, 37, 19])

In [34]:
%timeit data['나이']
%timeit data_rec['나이']
%timeit data_rec.나이

102 ns ± 4 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
2.55 µs ± 313 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.43 µs ± 256 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [30]:
data_rec

rec.array([('Alice', 25, 55. ), ('Bob', 45, 85.5), ('Cathy', 37, 68. ),
           ('Doug', 19, 61.5)],
          dtype=[('nam', '<U10'), ('age', '<i4'), ('weight', '<f8')])